### ISSUE TITLE
Support redux-saga v1.0.0-beta.1

### ISSUE THREAD

**Issue by anguyen1817** [jfairbank/redux-saga-test-plan#194]
Hi,

Thanks for this awesome library! I just updated redux saga to the latest beta version and, unfortunately, all my saga tests are failing. This is the error I got:
```

TypeError: Cannot read property 'then' of undefined
      
      at start (node_modules/redux-saga-test-plan/lib/expectSaga/index.js:601:31)
      at Object.run (node_modules/redux-saga-test-plan/lib/expectSaga/index.js:644:1)
      at Object.<anonymous> (__tests__/store/sagas/portal/workOrder.js:189:1)
      at tryCallTwo (node_modules/promise/lib/core.js:45:1)
      at doResolve (node_modules/promise/lib/core.js:200:9)
      at new Promise (node_modules/promise/lib/core.js:66:1)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
```

Do you know if there is any workaround for this?

**Comment by jfairbank** [comment]
Hi, @anguyen1817.

Unfortunately, I haven't had a chance to officially support 1.0 as I'm finishing up some other priorities.
I'd happily take a PR that could it get working. I don't think it will take a lot honestly. I'd eventually like to support some of the effect middleware functionality internally to reduce test plan's implementation but for now, supporting 1.0 with the current internals would be great.

**Comment by jfairbank** [comment]
Update: I have a branch with initial redux-saga 1.0 beta support [here](https://github.com/jfairbank/redux-saga-test-plan/tree/redux-saga-1.0)!

It's mostly ready. I just need to finish up some doc and CHANGELOG updates. I hope to get a release out soon this week (maybe even today).

**Comment by KASOGIT** [comment]
@jfairbank Hello, di you plained to support redux-sagas 1.0.x out of beta one day ? Best regards
