### ISSUE TITLE
state.set is not a function

### ISSUE THREAD

**Issue by danielrea** [jfairbank/redux-saga-test-plan#207]
Hi apologies if this has been covered before or is a misunderstanding on my side. Couldn't seem to find anything similar, so I guess it's just an issue with my implementation, if anyone could point me in the right direction it would be greatly appreciated. 

So I am using immutablejs alongside redux saga. I have my reducer setup like so:
`import { fromJS } from 'immutable';

import { types } from './constants';

//Reducers
export const initialState = fromJS({
  instance: {},
  provider: {},
  account: null,
  accountIndex: 1,
  balance: 0,
});

function web3Reducer(state = initialState, action) {
  switch (action.type) {
    case types.WEB3_STORE:
      return state
        .set('instance', action.instance)
    case types.ACCOUNT_STORE:
      return state
        .set('account', action.account)
    case types.BALANCE_STORE:
      return state
        .set('balance', action.balance)
    default:
      return state;
  }
}

export default web3Reducer;`

in my saga I am yielding 
` yield put(storeWeb3(web3));`

and my example test is setup as such
`it('handles reducer and stores state', () => {
  const storeState = expectSaga(web3InitTruffleHD, payload)
    .withReducer(web3Reducer, { web3: initialState })
  .run()
  .then((result) => {
    console.log('STORE STATE');
    console.log(result.storeState);
  })
})`

The error i'm getting when I run the test is this
`    console.error node_modules/redux-saga/lib/internal/utils.js:240
      uncaught at web3InitTruffleHD TypeError: state.set is not a function
          at web3Reducer (D:\Projects\oaken-platform-core\ducks\web3\reducer.js:18:10)
          at dispatch (D:\Projects\oaken-platform-core\node_modules\redux-saga-test-plan\lib\expectSaga\index.js:369:20)
          at D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\utils.js:265:12
          at D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\proc.js:500:52
          at exec (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\scheduler.js:25:5)
          at flush (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\scheduler.js:66:5)
          at asap (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\scheduler.js:39:5)
          at runPutEffect (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\proc.js:497:25)
          at runEffect (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\proc.js:446:184)
          at next (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\proc.js:326:9)
          at currCb (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\proc.js:399:7)
          at runSelectEffect (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\proc.js:710:7)
          at runEffect (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\proc.js:446:761)
          at next (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\proc.js:326:9)
          at proc (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\proc.js:281:3)
          at runSaga (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\runSaga.js:59:33)
          at start (D:\Projects\oaken-platform-core\node_modules\redux-saga-test-plan\lib\expectSaga\index.js:604:39)
          at Object.run (D:\Projects\oaken-platform-core\node_modules\redux-saga-test-plan\lib\expectSaga\index.js:649:5)
          at Object.<anonymous>.it (D:\Projects\oaken-platform-core\ducks\web3\sagas\tests\web3InitTruffleHDSaga.test.js:32:4)
          at Object.asyncFn (D:\Projects\oaken-platform-core\node_modules\jest-jasmine2\build\jasmine_async.js:108:37)
          at resolve (D:\Projects\oaken-platform-core\node_modules\jest-jasmine2\build\queue_runner.js:56:12)
          at new Promise (<anonymous>)
          at mapper (D:\Projects\oaken-platform-core\node_modules\jest-jasmine2\build\queue_runner.js:43:19)
          at promise.then (D:\Projects\oaken-platform-core\node_modules\jest-jasmine2\build\queue_runner.js:87:41)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
    console.error node_modules/redux-saga/lib/internal/utils.js:240
      uncaught at web3InitTruffleHD TypeError: state.set is not a function
          at web3Reducer (D:\Projects\oaken-platform-core\ducks\web3\reducer.js:21:10)
          at dispatch (D:\Projects\oaken-platform-core\node_modules\redux-saga-test-plan\lib\expectSaga\index.js:369:20)
          at D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\utils.js:265:12
          at D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\proc.js:500:52
          at exec (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\scheduler.js:25:5)
          at flush (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\scheduler.js:66:5)
          at asap (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\scheduler.js:39:5)
          at runPutEffect (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\proc.js:497:25)
          at runEffect (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\proc.js:446:184)
          at next (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\proc.js:326:9)
          at currCb (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\proc.js:399:7)
          at runSelectEffect (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\proc.js:710:7)
          at runEffect (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\proc.js:446:761)
          at next (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\proc.js:326:9)
          at proc (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\proc.js:281:3)
          at runSaga (D:\Projects\oaken-platform-core\node_modules\redux-saga\lib\internal\runSaga.js:59:33)
          at start (D:\Projects\oaken-platform-core\node_modules\redux-saga-test-plan\lib\expectSaga\index.js:604:39)
          at Object.run (D:\Projects\oaken-platform-core\node_modules\redux-saga-test-plan\lib\expectSaga\index.js:649:5)
          at Object.<anonymous>.it (D:\Projects\oaken-platform-core\ducks\web3\sagas\tests\web3InitTruffleHDSaga.test.js:32:4)
          at Object.asyncFn (D:\Projects\oaken-platform-core\node_modules\jest-jasmine2\build\jasmine_async.js:108:37)
          at resolve (D:\Projects\oaken-platform-core\node_modules\jest-jasmine2\build\queue_runner.js:56:12)
          at new Promise (<anonymous>)
          at mapper (D:\Projects\oaken-platform-core\node_modules\jest-jasmine2\build\queue_runner.js:43:19)
          at promise.then (D:\Projects\oaken-platform-core\node_modules\jest-jasmine2\build\queue_runner.js:87:41)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)`

select statements in the saga seem to be yielding from the initial state correctly, shouldn't the reducer also be able to interface with the state?

Thanks in advance.

**Comment by valentinacala** [comment]
@danielrea did you found an explanation or any workaround for this issue?
I'm getting a similar error when using `.reduce` method
