### ISSUE TITLE
TypeError: (0 , _utils.deprecate) is not a function

### ISSUE THREAD

**Issue by keyserfaty** [jfairbank/redux-saga-test-plan#218]
### How to reproduce

Hi! I'm trying to run the tests with jest and I'm getting this error:

```
  ● Test suite failed to run

    TypeError: (0 , _utils.deprecate) is not a function

      at Object.<anonymous> (node_modules/redux-saga/lib/internal/sagaHelpers/index.js:26:51)
      at Object.<anonymous> (node_modules/redux-saga/lib/internal/io.js:28:33)
      at Object.<anonymous> (node_modules/redux-saga/lib/effects.js:5:24)

```

If I look at the definition of `_utils` `deprecate` is certainly there but for some reason, it's not being able to find it. If I hardcode the definition of `deprecate` in `_utils` some other errors keep coming up related to some function of `_utils` being undefined. Any ideas?

### Packages
```
"redux-saga": "^0.16",
"redux-saga-test-plan": "^3.7.0",
"node": "8.1.0"
"webpack": "1.14.0",
"react": "16.2.0",
"jest": "17.0.2",
"babel-jest": "17.0.2",
```

**Comment by keyserfaty** [comment]
Sorry, was related to some local config.
