### ISSUE TITLE
TypeError: Cannot read property 'asEffect' of undefined

### ISSUE THREAD

**Issue by BaumVitaly** [jfairbank/redux-saga-test-plan#244]
`import {throwError} from 'redux-saga-test-plan/providers'` gives error with saga 1.0.0 tests

at Object.<anonymous> (node_modules/redux-saga-test-plan/lib/expectSaga/parseEffect.js:17:33)
      at Object.<anonymous> (node_modules/redux-saga-test-plan/lib/expectSaga/provideValue.js:12:20)
      at Object.<anonymous> (node_modules/redux-saga-test-plan/lib/expectSaga/providers/helpers.js:20:21)
      at Object.<anonymous> (node_modules/redux-saga-test-plan/lib/expectSaga/providers/index.js:8:16)
      at Object.<anonymous> (node_modules/redux-saga-test-plan/providers.js:1:45)

**Comment by spacesuitdiver** [comment]
@BaumVitaly did you figure this out? First time trying to use this library and I'm assuming I'm doing something wrong.

**Comment by BaumVitaly** [comment]
@spacesuitdiver Yes. if you will use redux-saga 0.16 version, then all be good, but if you use version more then 0.16 then you will got an error

**Comment by jp928** [comment]
please npm install 4.0beta2
