### ISSUE TITLE
Different behavior using jest it.each`` (Tagged Template Literal)

### ISSUE THREAD

**Issue by lcssanches** [jfairbank/redux-saga-test-plan#300]
Using Jest (CRA), I have write these two tests, which basically test the same.

I first write the first one, but then I found an alternative way to write jest `each`, which is more readable.

```
    it.each([[1, 1, 10], [5, 1, 10], [10, 1, 10]])(
        '#1-sagaSetVolume(%i) saga should set volume if it is between thresholds(1,10)',
        (volume, min, max) => {
            const threshold = { min, max };

            const mockAction = { payload: volume };

            testSaga(sagaSetVolume, mockAction)
                .next().select(getCurrentAudioLine)
                .next('audio-line').select(getVolumeThresholds)
                .next(threshold).call(wsApi.Sound.SetVolume, 'audio-line', mockAction.payload)
                .next().put(SoundActions.setVolumeSuccess(mockAction.payload))
                .next().isDone();
        }
    )

    it.each`
    volume | min  | max
    ${1}   | ${1} | ${10}
    ${5}   | ${1} | ${10}
    ${10}  | ${1} | ${10}
    `(
        '#2-sagaSetVolume($volume) saga should set volume if it is between thresholds($min,$max)',
        (volume, min, max) => {
            const threshold = { min, max };

            const mockAction = { payload: volume };

            testSaga(sagaSetVolume, mockAction)
                .next().select(getCurrentAudioLine)
                .next('audio-line').select(getVolumeThresholds)
                .next(threshold).call(wsApi.Sound.SetVolume, 'audio-line', mockAction.payload)
                .next().put(SoundActions.setVolumeSuccess(mockAction.payload))
                .next().isDone();
        });
    
```

But the second version does not run at all:
```
    √ #1-sagaSetVolume(1) saga should set volume if it is between thresholds(1,10) (7ms)
    √ #1-sagaSetVolume(5) saga should set volume if it is between thresholds(1,10) (1ms)
    √ #1-sagaSetVolume(10) saga should set volume if it is between thresholds(1,10)
    × #2-sagaSetVolume(1) saga should set volume if it is between thresholds(1,10) (5ms)
    × #2-sagaSetVolume(5) saga should set volume if it is between thresholds(1,10) (2ms)
    × #2-sagaSetVolume(10) saga should set volume if it is between thresholds(1,10)
/* ... */
    SagaTestError:
    Assertion 3 failed: expected call effect, but the saga yielded nothing

      100 |                 .next().select(getCurrentAudioLine)
      101 |                 .next('audio-line').select(getVolumeThresholds)
    > 102 |                 .next(threshold).call(wsApi.Sound.SetVolume, 'audio-line', mockAction.payload)
          |                                  ^
      103 |                 .next().put(SoundActions.setVolumeSuccess(mockAction.payload))
      104 |                 .next().isDone();
      105 |         });

      at new SagaTestError (node_modules/redux-saga-test-plan/lib/shared/SagaTestError.js:17:57)
      at assertSameEffect (node_modules/redux-saga-test-plan/lib/testSaga/assertSameEffect.js:20:11)
      at Object.call (node_modules/redux-saga-test-plan/lib/testSaga/index.js:66:40)
      at call (src/sagas/soundSagas.test.js:102:34)
```

I have no idea how `Tagged Template Literal` should affect the tests.

Link to jest documentation:

- [test.each(table)(name, fn, timeout)](https://jestjs.io/docs/en/next/api.html#1-testeachtable-name-fn-timeout)
- [test.each\`table\`(name, fn, timeout)](https://jestjs.io/docs/en/next/api.html#2-testeach-table-name-fn-timeout)

**Comment by jp928** [comment]
@lcssanches 
Thanks for reporting this but I just realise in the jest document they are using
```
({volume, min, max}) => {
....
}
```
whereas your test is
```
(volume, min, max) => {
....
}
```
notice you don't have bracket in the parameter.
Hope this will help you.
