### ISSUE TITLE
    TypeError: Cannot read property 'TAKE' of undefined

### ISSUE THREAD

**Issue by Eljoy** [jfairbank/redux-saga-test-plan#367]
```
  ● Test suite failed to run

    TypeError: Cannot read property 'TAKE' of undefined

      at Object.<anonymous> (node_modules/redux-saga-test-plan/lib/utils/asEffect.js:22:49)
      at Object.<anonymous> (node_modules/redux-saga-test-plan/lib/expectSaga/parseEffect.js:14:17)
```

"redux-saga": "^1.1.3"
"redux-saga-test-plan": "^4.0.1"

```
  test("promptOauthSignInFlow", () => {
    return expectSaga(authSaga)
      .run()
  });
```

```
function* authSaga() {
  yield all([
    takeLatest(signIn.request, promptOauthSignInFlow),
  ])
}

function* promptOauthSignInFlow() {
  try {
    yield call([authRepository(), 'signIn'])
  } catch (e) {
    yield put(signIn.failure(e))
  }
}
```

```
  test("promptOauthSignInFlow", () => {
    return expectSaga(authSaga)
      .run()
  });

```

**Comment by IgorGoloborodko1** [comment]
Same issue. Redux-saga 0.15, redux-saga-test-plan 4.0.1. Did anyone figure this one out?

**Comment by vadympetryshyn** [comment]
The same

**Comment by CrazyWood007** [comment]
Any suggestions?
