### ISSUE TITLE
getting TypeError: (0 , _reduxSaga.stdChannel) is not a function on simple example

### ISSUE THREAD

**Issue by gaurav341** [jfairbank/redux-saga-test-plan#371]
Logs are

TypeError: (0 , _reduxSaga.stdChannel) is not a function

    at expectSaga (/Users/gaurav.singh/Documents/projects/my-project/node_modules/redux-saga-test-plan/lib/expectSaga/index.js:123:47)
    at Object.<anonymous> (/Users/gaurav.singh/Documents/projects/my-project/src/redux/common/init/test/init.reducer.test.js:16:16)
    at Object.asyncJestTest (/Users/gaurav.singh/Documents/projects/my-project/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
    at /Users/gaurav.singh/Documents/projects/my-project/node_modules/jest-jasmine2/build/queueRunner.js:43:12
    at new Promise (<anonymous>)
    at mapper (/Users/gaurav.singh/Documents/projects/my-project/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
    at /Users/gaurav.singh/Documents/projects/my-project/node_modules/jest-jasmine2/build/queueRunner.js:73:41
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by ggbell** [comment]
This TypeError is thrown if you have an existing mock of redux-saga, e.g.

`jest.mock('redux-saga', () => ...);`

Try removing this and the error should disappear.
