### ISSUE TITLE
expectSaga.provide doesn't always go deep

### ISSUE THREAD

**Issue by publicJorn** [jfairbank/redux-saga-test-plan#85]
Hi, thanks for this testing library, it's already helped me out a lot!

I have successfully mocked `call` for some other deeply nested saga's; Eg. passing `.provide({provideInForkedTasks: true}, ...)` to a watcher as can be seen in the [provide tests](https://github.com/jfairbank/redux-saga-test-plan/blob/master/__tests__/expectSaga/provide.test.js)

However, in the example below, the provided `call` function is not passed all the way down to `fetchResults`:

**sagas.js**
```javascript
import { delay } from 'redux-saga'
import { takeEvery, put, call, select } from 'redux-saga/effects'
import request from 'utils/request'
import humps from 'humps'

import { FETCH_RESULT, fetchResultsSuccess, fetchResultsFailure } from './actions'
import { selectAnswers } from './selectors'

function* fetchAndWait () {
  // Get results from fetchResults, but wait at least 2 seconds before putting the action
  const [results] = yield [
    call(fetchResults),
    call(delay, 2000),
  ]
  yield put(results)
}

function* fetchResults () {
  let url = '/profile.json'

  if (process.env.NODE_ENV === 'development') {
    url = `/assets/media/frontend/json${url}`
  }

  const method = 'post'
  const data = yield select(selectAnswers)

  try {
    const result = yield call(request, { url, method, data })
    const convertedResult = humps.camelizeKeys(result)
    return fetchResultsSuccess(convertedResult)
  } catch (err) {
    return fetchResultsFailure(err)
  }
}

export function* watchFetchResults () {
  yield takeEvery(FETCH_RESULT, fetchAndWait)
}
```

**sagas.test.js**
```javascript
import { expectSaga } from 'redux-saga-test-plan'
import humps from 'humps'
import request from 'utils/request'

import { watchFetchResults } from '../sagas'
import * as actions from '../actions'

import mockProfile from 'environments/TasteProfile/__endpoints__/json/profile.json'

jest.mock('../selectors', () => {
  return {
    selectAnswers: () => {
      return { fake: 'answered questions object' }
    },
  }
})

describe('Given Result:Sagas', () => {
  const successfulRequest = (effect, next) => {
    console.log('using call...', effect)
    if (effect.fn === request) {
      return mockProfile
    }
    return next()
  }

  it('fetchResults() should put expected action on a successful request', () => {
    return expectSaga(watchFetchResults)
      // Mock successful request
      .provide({
        provideInForkedTasks: true,
        call: successfulRequest,
      })

      .put(actions.fetchResultsSuccess(humps.camelizeKeys(mockProfile)))

      .dispatch(actions.fetchResults())

      .run()
  })
})
```

**utils/request.js**
```javascript
export default function request (config = {}) {
  console.log('NOT BE GOING HERE!!')
  console.trace()
  // ...
}
```

Since I did get it to work on another test, I think it has to do with the construct in `fetchAndWait`. Here's an excerpt of the jest output. You can see that `call` is properly provided for in `fetchAndWait`, but `fetchResults` still calls the original `request.js`:

```
 FAIL  app/environments/TasteProfile/components/PersonalTasteProfile/tests/sagas.test.js

  ● Console

    console.log app/environments/TasteProfile/components/PersonalTasteProfile/tests/sagas.test.js:20

      using call... { context: null, fn: [Function: fetchResults], args: [] }

    console.log app/environments/TasteProfile/components/PersonalTasteProfile/tests/sagas.test.js:20

      using call... { context: null, fn: [Function: delay], args: [ 2000 ] }

    console.log app/environments/TasteProfile/components/PersonalTasteProfile/tests/sagas.test.js:20

      using call... { context: null, fn: [Function: fetchResults], args: [] }

    console.log app/environments/TasteProfile/components/PersonalTasteProfile/tests/sagas.test.js:20

      using call... { context: null, fn: [Function: delay], args: [ 2000 ] }

    console.log app/utils/request.js:23

      NOT BE GOING HERE!!

    console.error console.js:89

      Trace

          at request (/path/to/project/frontend/app/utils/request.js:23:707)
          at runCallEffect (/path/to/project/frontend/node_modules/redux-saga/lib/internal/proc.js:501:19)
          at runEffect (/path/to/project/frontend/node_modules/redux-saga/lib/internal/proc.js:429:399)
          at next (/path/to/project/frontend/node_modules/redux-saga/lib/internal/proc.js:310:9)
          at currCb (/path/to/project/frontend/node_modules/redux-saga/lib/internal/proc.js:383:7)
          at runSelectEffect (/path/to/project/frontend/node_modules/redux-saga/lib/internal/proc.js:682:7)
          at runEffect (/path/to/project/frontend/node_modules/redux-saga/lib/internal/proc.js:429:848)
          at next (/path/to/project/frontend/node_modules/redux-saga/lib/internal/proc.js:310:9)
          at proc (/path/to/project/frontend/node_modules/redux-saga/lib/internal/proc.js:265:3)
          at resolveIterator (/path/to/project/frontend/node_modules/redux-saga/lib/internal/proc.js:444:5)
    console.warn node_modules/redux-saga-test-plan/lib/expectSaga/index.js:215
      [WARNING]: Saga exceeded async timeout of 250ms
```

**Comment by jfairbank** [comment]
Hi, @publicJorn!

Thanks for opening this issue. I actually noticed this same problem with `call` late yesterday on one of my projects. I've started investigating and hope to have a fix soon.

**Comment by publicJorn** [comment]
Thanks for your swift reply!
I'll keep an eye out. If I can do anything to provide more details, let me know

**Comment by jfairbank** [comment]
This should be fixed in v2.3.5. Please let me know if you have any more issues @publicJorn. Thanks!

**Comment by eric-burel** [comment]
Hi, it does not seem to work when the `call` is nested into an `all` effect.
```js
export function* stuff(stuffId) {
   // When put in handleStuff, I am matched with matchers.call.fn(Stuffer.doStuff), but here I am not :(
    yield call(Stuffer.doStuff, stuffId);
}
export function* handleStuff(action) {
  yield all([call(stuff, 1), call(stuff, 2), call(stuff,3)]);
}
/**
 * When the queue have been updated, start consuming it from the top
 */
export function* watchStuff() {
  yield takeLatest('STUFF', handleStuff);
}

```

**Comment by saraht129** [comment]
I am seeing the same issue, my `select(state)` doesn't match when it's wrapped inside a 

    yield takeLatest('USER_ACTION', function*() {
        const myState = yield select(state);
    });

**Comment by hourliert** [comment]
I am seing the same issue than @eric-burel here with `3.6.0`.
Should we re-open this issue?

**Comment by eric-burel** [comment]
The lib creator seems to be looking for maintainer, I think the best would be to try to solve this ourselves ^^ I don't use this lib anymore (was on a client's project) but I can give help if you figure out where the bug could lie.
